### PR TITLE
Add DepMap combined RNAi dataset

### PR DESCRIPTION
**Pull request by jrouly**
Hey @kevinhu - I'd like to add support for the DepMap combined RNAi dataset (in addition to `drive` and `achilles`).

Here it is running locally:
```
import cancer_data
cancer_data.download_and_process('depmap_annotations')
sample_info.csv already downloaded and matches provided md5sum.
Processing depmap_annotations
INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
/Users/michel/redcell/cancer_data/venv/lib/python3.9/site-packages/tables/filters.py:326: FiltersWarning: compression library ``bzip2`` is not available; using ``zlib`` instead
  warnings.warn("compression library ``%s`` is not available; "
cancer_data.download_and_process('depmap_combined_rnai')
Downloading https://ndownloader.figshare.com/files/13515395
100%|██████████| 161M/161M [00:06<00:00, 23.5MiB/s]
D2_combined_gene_dep_scores.csv matches provided md5sum.
Processing depmap_combined_rnai
/Users/michel/redcell/cancer_data/venv/lib/python3.9/site-packages/tables/filters.py:326: FiltersWarning: compression library ``bzip2`` is not available; using ``zlib`` instead
  warnings.warn("compression library ``%s`` is not available; "
dcr = cancer_data.load('depmap_combined_rnai')
dcr.shape
Out[6]: (712, 17309)
```

### CODE REVIEW

**Comment by jrouly** [comment]
There are a couple issues still with the cell line name mapping actually, I'm getting a few `None`s. Will update.

**Review by kevinhu — APPROVED** [review]
Looks good! Thank you for the typo catches on the other files.

**Comment by kevinhu** [comment]
Please make sure the formatting's all good – looks like you should run Black.

**Comment by jrouly** [comment]
@kevinhu absolutely, done!

**Comment by kevinhu** [comment]
Thanks! Merged and published as 0.3.2 now.

**Pull request merged**
